commands:
  delete-windows-release:
    run: ./tools/delete-windows-release.sh
  release:
    argnames:
      - tag
    run: git tag -am $tag $tag && git push origin refs/tags/$tag
  release-next:
    run: |
      latest_version=$(git tag --list "v*" --sort "-refname" | head -1)
      next_version=$(echo ${latest_version} | awk -F. -v OFS=. '{$NF += 1 ; print}')
      printf "Release $next_version? (Current release is $latest_version) [yN] "
      read answer
      if [[ $answer =~ ^[Yy]$ ]]; then
        git tag -am $next_version $next_version && git push origin refs/tags/$next_version
      fi
  test:
    run: go test ./...

  update-deps:
    run: go get -u . && go mod tidy
